# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # Disable updates.
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # Disable updates.
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # Disable updates.
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # Disable updates.
