root = "."
tmp_dir = "tmp"

[build]
  full_bin = "./dist/synthetic-monitoring-agent --debug --api-server-address=localhost:4031 --api-insecure=true --dev=true"
  cmd = "make build"
  delay = 1000
  exclude_dir = [".chglog", ".github"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
