FROM --platform=$BUILDPLATFORM alpine:3.23.0@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375 AS build
RUN adduser -D -u 12345 -g 12345 sm

FROM --platform=$TARGETOS/$TARGETARCH scratch

ARG TARGETOS
ARG TARGETARCH

ADD ./dist/container-image.browser.${TARGETOS}-${TARGETARCH}.tar /
COPY --from=0 /etc/passwd /etc/passwd

USER sm
ENV K6_BROWSER_ARGS=no-sandbox,disable-dev-shm-usage

ENTRYPOINT ["tini", "--", "/usr/local/bin/synthetic-monitoring-agent"]
