FROM --platform=$BUILDPLATFORM alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715 AS build
RUN adduser -D -u 12345 -g 12345 sm

FROM --platform=$TARGETOS/$TARGETARCH scratch

ARG TARGETOS
ARG TARGETARCH

ADD ./dist/container-image.no-browser.${TARGETOS}-${TARGETARCH}.tar /
COPY --from=0 /etc/passwd /etc/passwd

USER sm
ENTRYPOINT ["/usr/local/bin/synthetic-monitoring-agent"]
