package scraper

// expectedRuntimeMetricCatalogueByAccountingClass describes the final published
// timeseries label contract for k6-backed checks when they are executed with an
// sm-k6 binary and browser-capable runtime.
var expectedRuntimeMetricCatalogueByAccountingClass = map[string]MetricLabelCatalogue{
	"browser": {
		"probe_all_duration_seconds_bucket":           []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":            []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                     []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                       []string{"config_version", "instance", "job", "probe"},
		"probe_browser_data_received":                 []string{"config_version", "from_cache", "from_prefetch_cache", "from_service_worker", "instance", "job", "method", "name", "probe", "proto", "resource_type", "scenario", "status", "url"},
		"probe_browser_data_sent":                     []string{"config_version", "instance", "job", "method", "name", "probe", "resource_type", "scenario", "url"},
		"probe_browser_http_req_duration":             []string{"config_version", "from_cache", "from_prefetch_cache", "from_service_worker", "instance", "job", "method", "name", "probe", "proto", "resource_type", "scenario", "status", "url"},
		"probe_browser_http_req_failed":               []string{"config_version", "from_cache", "from_prefetch_cache", "from_service_worker", "instance", "job", "method", "name", "probe", "proto", "resource_type", "scenario", "status", "url"},
		"probe_browser_web_vital_cls":                 []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_fcp":                 []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_fid":                 []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_inp":                 []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_lcp":                 []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_ttfb":                []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_check_success_rate":                    []string{"check", "config_version", "instance", "job", "probe", "scenario"},
		"probe_checks_total":                          []string{"check", "config_version", "instance", "job", "probe", "result", "scenario"},
		"probe_data_received_bytes":                   []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":                       []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":                      []string{"config_version", "instance", "job", "probe"},
		"probe_iteration_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_duration_seconds":            []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_script_all_duration_seconds_bucket":    []string{"config_version", "instance", "job", "le", "probe"},
		"probe_script_all_duration_seconds_count":     []string{"config_version", "instance", "job", "probe"},
		"probe_script_all_duration_seconds_sum":       []string{"config_version", "instance", "job", "probe"},
		"probe_script_duration_seconds":               []string{"config_version", "instance", "job", "probe"},
		"probe_success":                               []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                               []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"browser_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_browser_data_received":       []string{"config_version", "from_cache", "from_prefetch_cache", "from_service_worker", "instance", "job", "method", "name", "probe", "proto", "resource_type", "scenario", "status", "url"},
		"probe_browser_data_sent":           []string{"config_version", "instance", "job", "method", "name", "probe", "resource_type", "scenario", "url"},
		"probe_browser_http_req_duration":   []string{"config_version", "from_cache", "from_prefetch_cache", "from_service_worker", "instance", "job", "method", "name", "probe", "proto", "resource_type", "scenario", "status", "url"},
		"probe_browser_http_req_failed":     []string{"config_version", "from_cache", "from_prefetch_cache", "from_service_worker", "instance", "job", "method", "name", "probe", "proto", "resource_type", "scenario", "status", "url"},
		"probe_browser_web_vital_cls":       []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_fcp":       []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_fid":       []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_inp":       []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_lcp":       []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_browser_web_vital_ttfb":      []string{"config_version", "instance", "job", "name", "probe", "rating", "scenario", "url"},
		"probe_check_success_rate":          []string{"check", "config_version", "instance", "job", "probe", "scenario"},
		"probe_checks_total":                []string{"check", "config_version", "instance", "job", "probe", "result", "scenario"},
		"probe_data_received_bytes":         []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_iteration_duration_seconds":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_script_duration_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"multihttp": {
		"probe_all_duration_seconds_bucket":            []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":             []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":               []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                      []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                        []string{"config_version", "instance", "job", "probe"},
		"probe_check_success_rate":                     []string{"check", "config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_checks_total":                           []string{"check", "config_version", "instance", "job", "method", "probe", "result", "scenario", "url"},
		"probe_data_received_bytes":                    []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":                        []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":                       []string{"config_version", "instance", "job", "probe"},
		"probe_http_all_duration_seconds_bucket":       []string{"config_version", "instance", "job", "le", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_all_duration_seconds_count":        []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_all_duration_seconds_sum":          []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_duration_seconds":                  []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_error_code":                        []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_got_expected_response":             []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_info":                              []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed":                   []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed_total":             []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_total":                    []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_ssl":                               []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_status_code":                       []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_all_duration_seconds_count":  []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_duration_seconds":            []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_version":                           []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_iteration_all_duration_seconds_bucket":  []string{"config_version", "instance", "job", "le", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_count":   []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_sum":     []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_duration_seconds":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_script_all_duration_seconds_bucket":     []string{"config_version", "instance", "job", "le", "probe"},
		"probe_script_all_duration_seconds_count":      []string{"config_version", "instance", "job", "probe"},
		"probe_script_all_duration_seconds_sum":        []string{"config_version", "instance", "job", "probe"},
		"probe_script_duration_seconds":                []string{"config_version", "instance", "job", "probe"},
		"probe_success":                                []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                                []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"multihttp_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_check_success_rate":          []string{"check", "config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_checks_total":                []string{"check", "config_version", "instance", "job", "method", "probe", "result", "scenario", "url"},
		"probe_data_received_bytes":         []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":       []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_error_code":             []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_got_expected_response":  []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_info":                   []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed":        []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed_total":  []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_total":         []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_ssl":                    []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_status_code":            []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_duration_seconds": []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_version":                []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_iteration_duration_seconds":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_script_duration_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"scripted": {
		"probe_all_duration_seconds_bucket":            []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":             []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":               []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                      []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                        []string{"config_version", "instance", "job", "probe"},
		"probe_check_success_rate":                     []string{"check", "config_version", "instance", "job", "probe", "scenario"},
		"probe_checks_total":                           []string{"check", "config_version", "instance", "job", "probe", "result", "scenario"},
		"probe_data_received_bytes":                    []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":                        []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":                       []string{"config_version", "instance", "job", "probe"},
		"probe_http_all_duration_seconds_bucket":       []string{"config_version", "instance", "job", "le", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_all_duration_seconds_count":        []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_all_duration_seconds_sum":          []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_duration_seconds":                  []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_error_code":                        []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_got_expected_response":             []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_info":                              []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed":                   []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed_total":             []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_total":                    []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_ssl":                               []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_status_code":                       []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_all_duration_seconds_count":  []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_duration_seconds":            []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_version":                           []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_iteration_all_duration_seconds_bucket":  []string{"config_version", "instance", "job", "le", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_count":   []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_sum":     []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_duration_seconds":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_script_all_duration_seconds_bucket":     []string{"config_version", "instance", "job", "le", "probe"},
		"probe_script_all_duration_seconds_count":      []string{"config_version", "instance", "job", "probe"},
		"probe_script_all_duration_seconds_sum":        []string{"config_version", "instance", "job", "probe"},
		"probe_script_duration_seconds":                []string{"config_version", "instance", "job", "probe"},
		"probe_success":                                []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                                []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"scripted_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_check_success_rate":          []string{"check", "config_version", "instance", "job", "probe", "scenario"},
		"probe_checks_total":                []string{"check", "config_version", "instance", "job", "probe", "result", "scenario"},
		"probe_data_received_bytes":         []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":       []string{"config_version", "instance", "job", "method", "name", "phase", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_error_code":             []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_got_expected_response":  []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_info":                   []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed":        []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_failed_total":  []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_requests_total":         []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_ssl":                    []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_status_code":            []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_total_duration_seconds": []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_http_version":                []string{"config_version", "instance", "job", "method", "name", "probe", "proto", "scenario", "status", "tls_version", "url"},
		"probe_iteration_duration_seconds":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_script_duration_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
}
