package scraper

// expectedFixtureMetricCatalogueByAccountingClass describes the final published timeseries
// label contract after Scraper.collectData applies shared SM labels.
//
// Traceroute classes are intentionally omitted for now because the repository's
// Linux-backed test environment used here lacks the capabilities required to run
// traceroute probes end-to-end.
var expectedFixtureMetricCatalogueByAccountingClass = map[string]MetricLabelCatalogue{
	"browser": {
		"probe_all_duration_seconds_bucket":           []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":            []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                     []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                       []string{"config_version", "instance", "job", "probe"},
		"probe_data_received_bytes":                   []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":                       []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":                      []string{"config_version", "instance", "job", "probe"},
		"probe_iteration_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_duration_seconds":            []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_success":                               []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                               []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"browser_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_data_received_bytes":         []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_iteration_duration_seconds":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"dns": {
		"probe_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                  []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_additional_rrs":                 []string{"config_version", "instance", "job", "probe"},
		"probe_dns_all_duration_seconds_bucket":    []string{"config_version", "instance", "job", "le", "phase", "probe"},
		"probe_dns_all_duration_seconds_count":     []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_dns_all_duration_seconds_sum":       []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_dns_answer_rrs":                     []string{"config_version", "instance", "job", "probe"},
		"probe_dns_authority_rrs":                  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_duration_seconds":               []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_dns_query_succeeded":                []string{"config_version", "instance", "job", "probe"},
		"probe_dns_serial":                         []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                   []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                        []string{"config_version", "instance", "job", "probe"},
		"probe_success":                            []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                            []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"dns_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_dns_additional_rrs":          []string{"config_version", "instance", "job", "probe"},
		"probe_dns_answer_rrs":              []string{"config_version", "instance", "job", "probe"},
		"probe_dns_authority_rrs":           []string{"config_version", "instance", "job", "probe"},
		"probe_dns_duration_seconds":        []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_dns_lookup_time_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_dns_query_succeeded":         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_serial":                  []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                 []string{"config_version", "instance", "job", "probe"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"grpc": {
		"probe_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                  []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                   []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_all_duration_seconds_bucket":   []string{"config_version", "instance", "job", "le", "phase", "probe"},
		"probe_grpc_all_duration_seconds_count":    []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_all_duration_seconds_sum":      []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_duration_seconds":              []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_healthcheck_response":          []string{"config_version", "instance", "job", "probe", "serving_status"},
		"probe_grpc_ssl":                           []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_status_code":                   []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                        []string{"config_version", "instance", "job", "probe"},
		"probe_success":                            []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                            []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"grpc_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_duration_seconds":       []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_healthcheck_response":   []string{"config_version", "instance", "job", "probe", "serving_status"},
		"probe_grpc_ssl":                    []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_status_code":            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                 []string{"config_version", "instance", "job", "probe"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"grpc_ssl": {
		"probe_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                  []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                   []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_all_duration_seconds_bucket":   []string{"config_version", "instance", "job", "le", "phase", "probe"},
		"probe_grpc_all_duration_seconds_count":    []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_all_duration_seconds_sum":      []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_duration_seconds":              []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_healthcheck_response":          []string{"config_version", "instance", "job", "probe", "serving_status"},
		"probe_grpc_ssl":                           []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_status_code":                   []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                        []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_earliest_cert_expiry":           []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_info":                []string{"config_version", "fingerprint_sha256", "instance", "issuer", "job", "probe", "serialnumber", "subject", "subjectalternative"},
		"probe_success":                            []string{"config_version", "instance", "job", "probe"},
		"probe_tls_version_info":                   []string{"config_version", "instance", "job", "probe", "version"},
		"sm_check_info":                            []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"grpc_ssl_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_duration_seconds":       []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_grpc_healthcheck_response":   []string{"config_version", "instance", "job", "probe", "serving_status"},
		"probe_grpc_ssl":                    []string{"config_version", "instance", "job", "probe"},
		"probe_grpc_status_code":            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                 []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_earliest_cert_expiry":    []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_info":         []string{"config_version", "fingerprint_sha256", "instance", "issuer", "job", "probe", "serialnumber", "subject", "subjectalternative"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"probe_tls_version_info":            []string{"config_version", "instance", "job", "probe", "version"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"http": {
		"probe_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                  []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                   []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":                []string{"config_version", "instance", "job", "probe"},
		"probe_http_all_duration_seconds_bucket":   []string{"config_version", "instance", "job", "le", "phase", "probe"},
		"probe_http_all_duration_seconds_count":    []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_all_duration_seconds_sum":      []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_content_length":                []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":              []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_redirects":                     []string{"config_version", "instance", "job", "probe"},
		"probe_http_ssl":                           []string{"config_version", "instance", "job", "probe"},
		"probe_http_status_code":                   []string{"config_version", "instance", "job", "probe"},
		"probe_http_uncompressed_body_length":      []string{"config_version", "instance", "job", "probe"},
		"probe_http_version":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                        []string{"config_version", "instance", "job", "probe"},
		"probe_success":                            []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                            []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"http_basic": {
		"probe_all_duration_seconds_bucket":   []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":      []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":             []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":               []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":       []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":              []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":           []string{"config_version", "instance", "job", "probe"},
		"probe_http_content_length":           []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":         []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_redirects":                []string{"config_version", "instance", "job", "probe"},
		"probe_http_ssl":                      []string{"config_version", "instance", "job", "probe"},
		"probe_http_status_code":              []string{"config_version", "instance", "job", "probe"},
		"probe_http_uncompressed_body_length": []string{"config_version", "instance", "job", "probe"},
		"probe_http_version":                  []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                  []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                   []string{"config_version", "instance", "job", "probe"},
		"probe_success":                       []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                       []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"http_ssl": {
		"probe_all_duration_seconds_bucket":             []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":                []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                       []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket":      []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":       []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":                 []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                        []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":                     []string{"config_version", "instance", "job", "probe"},
		"probe_http_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "phase", "probe"},
		"probe_http_all_duration_seconds_count":         []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_content_length":                     []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":                   []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_last_modified_timestamp_seconds":    []string{"config_version", "instance", "job", "probe"},
		"probe_http_redirects":                          []string{"config_version", "instance", "job", "probe"},
		"probe_http_ssl":                                []string{"config_version", "instance", "job", "probe"},
		"probe_http_status_code":                        []string{"config_version", "instance", "job", "probe"},
		"probe_http_uncompressed_body_length":           []string{"config_version", "instance", "job", "probe"},
		"probe_http_version":                            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                             []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_earliest_cert_expiry":                []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_expiry_timestamp_seconds": []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_info":                     []string{"config_version", "fingerprint_sha256", "instance", "issuer", "job", "probe", "serialnumber", "subject", "subjectalternative"},
		"probe_success":                                 []string{"config_version", "instance", "job", "probe"},
		"probe_tls_cipher_info":                         []string{"cipher", "config_version", "instance", "job", "probe"},
		"probe_tls_version_info":                        []string{"config_version", "instance", "job", "probe", "version"},
		"sm_check_info":                                 []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"http_ssl_basic": {
		"probe_all_duration_seconds_bucket":             []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":                []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                       []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":                 []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                        []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":                     []string{"config_version", "instance", "job", "probe"},
		"probe_http_content_length":                     []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":                   []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_http_last_modified_timestamp_seconds":    []string{"config_version", "instance", "job", "probe"},
		"probe_http_redirects":                          []string{"config_version", "instance", "job", "probe"},
		"probe_http_ssl":                                []string{"config_version", "instance", "job", "probe"},
		"probe_http_status_code":                        []string{"config_version", "instance", "job", "probe"},
		"probe_http_uncompressed_body_length":           []string{"config_version", "instance", "job", "probe"},
		"probe_http_version":                            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                             []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_earliest_cert_expiry":                []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_expiry_timestamp_seconds": []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_info":                     []string{"config_version", "fingerprint_sha256", "instance", "issuer", "job", "probe", "serialnumber", "subject", "subjectalternative"},
		"probe_success":                                 []string{"config_version", "instance", "job", "probe"},
		"probe_tls_cipher_info":                         []string{"cipher", "config_version", "instance", "job", "probe"},
		"probe_tls_version_info":                        []string{"config_version", "instance", "job", "probe", "version"},
		"sm_check_info":                                 []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"multihttp": {
		"probe_all_duration_seconds_bucket":           []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":            []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                     []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                       []string{"config_version", "instance", "job", "probe"},
		"probe_data_received_bytes":                   []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":                       []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":                      []string{"config_version", "instance", "job", "probe"},
		"probe_http_all_duration_seconds_bucket":      []string{"config_version", "instance", "job", "le", "method", "phase", "probe", "scenario", "url"},
		"probe_http_all_duration_seconds_count":       []string{"config_version", "instance", "job", "method", "phase", "probe", "scenario", "url"},
		"probe_http_all_duration_seconds_sum":         []string{"config_version", "instance", "job", "method", "phase", "probe", "scenario", "url"},
		"probe_http_duration_seconds":                 []string{"config_version", "instance", "job", "method", "phase", "probe", "scenario", "url"},
		"probe_http_info":                             []string{"config_version", "expected_response", "instance", "job", "method", "probe", "proto", "scenario", "url"},
		"probe_http_requests_failed_total":            []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_requests_total":                   []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_ssl":                              []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_status_code":                      []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_version":                          []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_iteration_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_duration_seconds":            []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_success":                               []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                               []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"multihttp_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_data_received_bytes":         []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_http_duration_seconds":       []string{"config_version", "instance", "job", "method", "phase", "probe", "scenario", "url"},
		"probe_http_info":                   []string{"config_version", "expected_response", "instance", "job", "method", "probe", "proto", "scenario", "url"},
		"probe_http_requests_failed_total":  []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_requests_total":         []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_ssl":                    []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_status_code":            []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_http_version":                []string{"config_version", "instance", "job", "method", "probe", "scenario", "url"},
		"probe_iteration_duration_seconds":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"ping": {
		"probe_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                  []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                   []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_all_duration_seconds_bucket":   []string{"config_version", "instance", "job", "le", "phase", "probe"},
		"probe_icmp_all_duration_seconds_count":    []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_icmp_all_duration_seconds_sum":      []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_icmp_duration_rtt_max_seconds":      []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_rtt_min_seconds":      []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_rtt_stddev_seconds":   []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_seconds":              []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_icmp_packets_received_count":        []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_packets_sent_count":            []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_reply_hop_limit":               []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                        []string{"config_version", "instance", "job", "probe"},
		"probe_success":                            []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                            []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"ping_basic": {
		"probe_all_duration_seconds_bucket":      []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":       []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":          []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                 []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_rtt_max_seconds":    []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_rtt_min_seconds":    []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_rtt_stddev_seconds": []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_duration_seconds":            []string{"config_version", "instance", "job", "phase", "probe"},
		"probe_icmp_packets_received_count":      []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_packets_sent_count":          []string{"config_version", "instance", "job", "probe"},
		"probe_icmp_reply_hop_limit":             []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                     []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                      []string{"config_version", "instance", "job", "probe"},
		"probe_success":                          []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                          []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"scripted": {
		"probe_all_duration_seconds_bucket":           []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":            []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                     []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                       []string{"config_version", "instance", "job", "probe"},
		"probe_data_received_bytes":                   []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":                       []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":                      []string{"config_version", "instance", "job", "probe"},
		"probe_iteration_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_iteration_duration_seconds":            []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_success":                               []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                               []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"scripted_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_data_received_bytes":         []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_data_sent_bytes":             []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_iteration_duration_seconds":  []string{"config_version", "instance", "job", "probe", "scenario"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"tcp": {
		"probe_all_duration_seconds_bucket":        []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":         []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                  []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                   []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":                []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                       []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                        []string{"config_version", "instance", "job", "probe"},
		"probe_success":                            []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                            []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"tcp_basic": {
		"probe_all_duration_seconds_bucket": []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":  []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":    []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":           []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":             []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":     []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":            []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":         []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                 []string{"config_version", "instance", "job", "probe"},
		"probe_success":                     []string{"config_version", "instance", "job", "probe"},
		"sm_check_info":                     []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"tcp_ssl": {
		"probe_all_duration_seconds_bucket":             []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":                []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                       []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_bucket":      []string{"config_version", "instance", "job", "le", "probe"},
		"probe_dns_lookup_all_time_seconds_count":       []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_all_time_seconds_sum":         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":                 []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                        []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":                     []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                             []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_earliest_cert_expiry":                []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_expiry_timestamp_seconds": []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_info":                     []string{"config_version", "fingerprint_sha256", "instance", "issuer", "job", "probe", "serialnumber", "subject", "subjectalternative"},
		"probe_success":                                 []string{"config_version", "instance", "job", "probe"},
		"probe_tls_version_info":                        []string{"config_version", "instance", "job", "probe", "version"},
		"sm_check_info":                                 []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
	"tcp_ssl_basic": {
		"probe_all_duration_seconds_bucket":             []string{"config_version", "instance", "job", "le", "probe"},
		"probe_all_duration_seconds_count":              []string{"config_version", "instance", "job", "probe"},
		"probe_all_duration_seconds_sum":                []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_count":                       []string{"config_version", "instance", "job", "probe"},
		"probe_all_success_sum":                         []string{"config_version", "instance", "job", "probe"},
		"probe_dns_lookup_time_seconds":                 []string{"config_version", "instance", "job", "probe"},
		"probe_duration_seconds":                        []string{"config_version", "instance", "job", "probe"},
		"probe_failed_due_to_regex":                     []string{"config_version", "instance", "job", "probe"},
		"probe_ip_addr_hash":                            []string{"config_version", "instance", "job", "probe"},
		"probe_ip_protocol":                             []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_earliest_cert_expiry":                []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_expiry_timestamp_seconds": []string{"config_version", "instance", "job", "probe"},
		"probe_ssl_last_chain_info":                     []string{"config_version", "fingerprint_sha256", "instance", "issuer", "job", "probe", "serialnumber", "subject", "subjectalternative"},
		"probe_success":                                 []string{"config_version", "instance", "job", "probe"},
		"probe_tls_version_info":                        []string{"config_version", "instance", "job", "probe", "version"},
		"sm_check_info":                                 []string{"check_name", "config_version", "frequency", "geohash", "instance", "job", "probe", "region"},
	},
}
