version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - run: make test

  build:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - run: make build

  deploy:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: make docker
      - run:
          name: build packages
          command: make package
      - deploy:
          command: |
            docker login -u $DOCKER_USER -p "$DOCKER_PASS"
            make docker-push
            export GCS_KEY_DIR=$(pwd)/keys
            mkdir -p $GCS_KEY_DIR
            echo "$GCS_KEY" > $GCS_KEY_DIR/gcs-key.json
            make publish-packages

workflows:
  version: 2

  test-and-build-everything:
    jobs:
      - lint:
          filters:
            branches:
              ignore: master
      - test:
          filters:
            branches:
              ignore: master
      - build:
          requires:
            - test
            - lint
          filters:
            branches:
              ignore: master

  test-and-deploy-master:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master

  test-and-deploy-tagged:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
