version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - run: make test

  build:
    docker:
      - image: circleci/golang:1.13.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: make docker
      - run:
          name: build packages
          command: make package
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p "$DOCKER_PASS" https://us.gcr.io
              docker push us.gcr.io/kubernetes-dev/synthetic-monitoring-agent:latest
              export GCS_KEY_DIR=$(pwd)/keys
              mkdir -p $GCS_KEY_DIR
              echo "$DOCKER_PASS" > $GCS_KEY_DIR/gcs-key.json
              make publish-packages
            fi

workflows:
  version: 2
  test_and_build:
    jobs:
      - lint
      - test
      - build:
          requires:
            - test
            - lint
