name: 'Save Go cache'
description: 'Save Go cache to be used in future runs'
inputs:
  key:
    description: "The key to use when updating the cache"
    required: true
  path:
    description: "The path or paths to be added to the cache"
    required: true
runs:
  using: "composite"
  steps:
    - name: Save Go cache
      uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        key: ${{ inputs.key }}
        path: ${{ inputs.path }}
