#!/bin/sh

set -e
set -u

syntax() {
	cat <<-EOT
Syntax:

	$0 <gh_repo_name> <target>
EOT
}

gh_repo_name=$1
target=$2
src=${3:-${PWD}/scripts/configs/drone/main.jsonnet}

test -z "${target}" && syntax && exit 1

drone_json=$(mktemp)
drone_yaml=$(mktemp)

trap 'rm -f "${drone_json}" "${drone_yaml}"' EXIT

jsonnet \
	--jpath "${PWD}/scripts/configs/drone/vendor" \
	"${src}" > "${drone_json}"
drone jsonnet --stream --format --source "${drone_json}" --target "${drone_yaml}"
drone lint --trusted "${drone_yaml}"
drone sign --save "${gh_repo_name}" "${drone_yaml}"
mv "${drone_yaml}" "${target}"
