#!/bin/sh

set -e
set -u

if test ! -d ./cmd/version ; then
	git describe --dirty --tags --long --always --abbrev=12
else
	tmpdir=$(mktemp -d)
	trap 'rm -rf "$tmpdir"' EXIT

	go build -o "$tmpdir/version" ./cmd/version &&
		"$tmpdir/version" 2>&1 ||
		echo "unknown"
fi
