enable:

run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    # - gocognit
    - gocyclo
    - gofmt
    # - gofumpt
    - goimports
    # - golint
    - goprintffuncname
    # - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  goconst:
    ignore-tests: false
    min-len: 5
    min-occurrences: 5
  gocyclo:
    min-complexity: 20
  golint:
    ignore-tests: false
    min-confidence: 3
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - assignOp
      - badCall
      - badCond
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - defaultCaseOrder
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - exitAfterDefer
      - flagDeref
      - flagName
      - ifElseChain
      - mapKey
      - newDeref
      - offBy1
      - regexpMust
      - ruleguard
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeSwitchVar
      - underef
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
    settings:
      ruleguard:
        rules: "scripts/go/configs/rules.go"

issues:
  exclude:
    - "(func|method|type|var|struct field|func parameter|method parameter) [^ ]+ should be .*"
  # new: true
  # new-from-rev: v0.0.3
