apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-agent-1
  namespace: synthetic-monitoring
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: sm-agent-1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: sm-agent-1
    spec:
      containers:
        - args:
            - --api-server-address=$(API_SERVER)
            - --api-token=$(API_TOKEN)
            - --verbose=true
            # Uncomment to listen on all interfaces. This exposes metrics and debugging endpoints to the cluster, so it
            # should only be done on trusted clusters or with network policies set in place.
            # - --listen-address=0.0.0.0:4050
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: api-token
                  name: sm-agent-1
            - name: API_SERVER
              valueFrom:
                secretKeyRef:
                  key: api-server
                  name: sm-agent-1
          image: grafana/synthetic-monitoring-agent:latest
          name: agent
          ports:
            - containerPort: 4050
              name: http-metrics
          securityContext:
            capabilities:
              add:
                - NET_RAW # Needed for ICMP (ping and traceroute) checks.
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 12345 # https://github.com/grafana/synthetic-monitoring-agent/blob/main/Dockerfile#L24
          # Readiness/liveness probes can be enabled to show the agent as not ready if it cannot successfully connect
          # to the Grafana Synthetic Monitoring API. Enabling this probes requires configuring the agent to listen on
          # all interfaces, so they are commented out by default.
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 4050
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 4050
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: tmp
              subPath: tmp
              mountPath: /tmp
            # Uncomment the following volumeMount if you are using the -browser image, as Chromium needs to be able to
            # write temporary files.
            # - name: tmp
            #   subPath: home-sm
            #   mountPath: /home/sm
      volumes:
        - name: tmp
          emptyDir: {}
